language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno

script:
- for e in example/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done