language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio update

env:
- BOARD=uno
    - PLATFORMIO_CI_SRC=GPIO.h
    - PLATFORMIO_CI_SRC=GPIO.c
    - PLATFORMIO_CI_SRC=example/main.ino

script:

    - platformio ci --board=uno --lib=./
